### ISSUE TITLE
SSPB 3.1.0 is marked as compatible with Minecraft 1.19 and 1.19.1, despite being impossible to use on those versions

### ISSUE THREAD

**Issue by floral-qua-floral** [Rynnavinx/sodium-shadowy-path-blocks#10]
SSPB 3.1.0 requires Sodium version 0.4.3 or later, which is only available for 1.19.2, making that the only Minecraft version with which SSPB 3.1.0 can be used. However, it is marked as supporting 1.19-1.19.2.

**Comment by Rynnavinx** [comment]
Though I guess not officially, Sodium 0.4.3 seemed to work fine on 1.19 and 1.19.1, which is why I listed them. 0.4.4 does specify compatibility with 1.19 and 1.19.1 on Modrinth though, so I'll keep it marked as compatible
