### ISSUE TITLE
Support for 1.19.4

### ISSUE THREAD

**Issue by Draacoun** [Rynnavinx/sodium-shadowy-path-blocks#12]
When you guys have time, consider updating the mod for Minecraft 1.19.4. No pressure. 💪

**Comment by Rynnavinx** [comment]
Hi, sorry for late reply, but it should still work on 1.19.4.

Have you tried it and had it not work?

**Comment by Draacoun** [comment]
I tried a few days after the 1.19.4 release, and it didn't work since the mod was in 1.19.2. I just tried it here and it's working now (I don't know if you changed something or I made something wrong back when I tried)

![2023-04-27_19 46 15](https://user-images.githubusercontent.com/47063486/235006830-7ab4a8d2-1485-4ce3-b678-8097ad868db8.png)

**Comment by Rynnavinx** [comment]
Changed nothing, but glad that you got it working 👍
