### ISSUE TITLE
crash report

### ISSUE THREAD

**Issue by Dabbpool** [Rynnavinx/sodium-shadowy-path-blocks#13]
since the launcher update yesterday it's been giving me errors and I've had a few updates and I've narrowed it down to this mod here's my last report before everything was stable. 
[crash-2023-05-17_08.12.33-client.txt](https://github.com/Rynnavinx/sodium-shadowy-path-blocks/files/11498062/crash-2023-05-17_08.12.33-client.txt)

**Comment by Dabbpool** [comment]
so it seems that the problem is that the curse client thinks it needs to update from 3.1.0 to 3.0.0 and when it updates it crashes but when i downgrade it asks me to update

**Comment by Rynnavinx** [comment]
3.0.0 is not compatible with any sodium version 0.4.3 and above, and you're using 0.4.4. Not sure what circumstances you're in where it's forcing you to downgrade from 3.1.0 to 3.0.0. 

3.1.0 is the latest version for MC1.19.2 on the Curseforge page, so I'm not sure why it would force you to use 3.0.0. I'm not really sure how the Curse client works. Could it maybe be that you're playing a modpack using the wrong version of SSPB? Is it possible to just not "update" to the older version?

In any case, This doesn't seem to be something I can do anything about, sorry.
