### ISSUE TITLE
About 1.20.4

### ISSUE THREAD

**Issue by vico93** [Rynnavinx/sodium-shadowy-path-blocks#18]
Sorry about the question, but is there any updates for 1.20.4 (Sodium 0.5.5) on the radar?

**Comment by Rynnavinx** [comment]
The latest SSPB version should still work for those versions. I just hadn't gotten around to listing them in the mod info until now, sorry. Unless there's a specific issue you're having?

**Comment by vico93** [comment]
Very sorry for opening this issue then. I assumed all mods that touch the graphic stuff of the game in any way would have broken in 1.20.3 due to the changes introduced by Mojang. If its not the case, i will add to my pack. If i have any issues i will let you know! Thanks a lot, and sorry one more time!
