### ISSUE TITLE
Clarify which shadowyness value is the Minecraft default (how strong vanilla's shadows are)

### ISSUE THREAD

**Issue by mrjasonn** [Rynnavinx/sodium-shadowy-path-blocks#19]
Please clarify which shadowyness value is also the Minecraft default (how strong vanilla's shadows are) in the options so people know better how to make their game look more vanilla.

**Comment by Rynnavinx** [comment]
Unfortunately, there isn't really a percentage that perfectly correlates to the "Minecraft default". Sodium's smooth lighting works differently than vanilla's smooth lighting (you can check the gifs on the Modrinth or Curseforge pages to see the difference), so even at the same percentage, blocks might be darker than vanilla in one scenario, and lighter in a different scenario. 

The default of 85% is what I believed to be a safe balance in most cases.

**Comment by mrjasonn** [comment]
> Unfortunately, there isn't really a percentage that perfectly correlates to the "Minecraft default". Sodium's smooth lighting works differently than vanilla's smooth lighting (you can check the gifs on the Modrinth or Curseforge pages to see the difference), so even at the same percentage, blocks might be darker than vanilla in one scenario, and lighter in a different scenario.
> 
> The default of 85% is what I believed to be a safe balance in most cases.

Would 100% be closer to vanilla though in most cases you usually see like village paths though? @Rynnavinx

**Comment by Rynnavinx** [comment]
> Would 100% be closer to vanilla though in most cases you usually see like village paths though? @Rynnavinx

Yes

**Comment by mrjasonn** [comment]
> > Would 100% be closer to vanilla though in most cases you usually see like village paths though? @Rynnavinx
> 
> Yes

Can you please also tell people in the options about this, while keeping the safe balance as default? As people would probably like to know

**Comment by Rynnavinx** [comment]
Added in da28ec2
