### ISSUE TITLE
Disable shadowyness toggle when vanilla path lighting is used

### ISSUE THREAD

**Issue by mrjasonn** [Rynnavinx/sodium-shadowy-path-blocks#21]
Because the shadowyness can't be set when using the vanilla setting, it should be disabled and added to the description that it will be disabled when that option is enabled. If you don't want to disable the toggle if so, please at least tell people in that toggle's description that if you use the vanilla one the toggle doesn't affect it. If this is actually a bug that the vanilla one isn't affected by the toggle, then the vanilla one should be affected by the toggle.

**Comment by Rynnavinx** [comment]
This sounds like a good idea, but with the way the Sodium options screen works, it doesn't seem possible to make an option switch between enabled/disabled without restarting the game. I could probably do some stuff to make it work, but honestly, it doesn't seem like a big enough deal to implement and maintain this.

Also, it is mentioned in the vanilla lighting tooltip that it disables the effect of shadowyness on path blocks, but I can add it to the shadowyness tooltip too, sure.
