### ISSUE TITLE
Update to 1.20.5

### ISSUE THREAD

**Issue by mrjasonn** [Rynnavinx/sodium-shadowy-path-blocks#23]
@Rynnavinx please do ASAP, people really want this mod to be updated
If you can help out and you want to get this mod updated, you might want to create a pull request to update this mod to speed up the process.

**Comment by Rynnavinx** [comment]
Is there something specifically that isn't compatible with 1.20.5 (or I guess soon to be 1.20.6)?

I do plan on updating the mod, but as far as functionality goes, SSPB 3.2.1 still appears to still work fine in 1.20.5 for me.

**Comment by mrjasonn** [comment]
> Is there something specifically that isn't compatible with 1.20.5 (or I guess soon to be 1.20.6)?
> 
> I do plan on updating the mod, but as far as functionality goes, SSPB 3.2.1 still appears to still work fine in 1.20.5 for me.

This is still an issue, I have attached the crash report and log (log includes mod list, with all these mods without SSPB it works fine, but with SSPB it crashes when load into world, to be very specific I have only tested on loading into Hypixel and without SSPB loading into Hypixel works fine) @Rynnavinx 
[crash-2024-04-27_14.48.29-client.txt](https://github.com/Rynnavinx/sodium-shadowy-path-blocks/files/15137334/crash-2024-04-27_14.48.29-client.txt)
[latest.log](https://github.com/Rynnavinx/sodium-shadowy-path-blocks/files/15137336/latest.log)

**Comment by mrjasonn** [comment]
@Rynnavinx Update: apparently the links were broken if you already did try to click them, if one or both didn't work, please click again

**Comment by ghost** [comment]
I can confirm that this is an issue.

**Comment by Rynnavinx** [comment]
Fixed in release 3.3.0
