### ISSUE TITLE
1.16.5 version plz

### ISSUE THREAD

**Issue by JocuperDARY** [Rynnavinx/sodium-shadowy-path-blocks#3]
adding support for 1.16.5, plz~
I'm playing 1.16.5 fabric with shader, which means I should install sodium, but I actually prefer the vanilla lighting. Is there a plan to add support for 1.16.5?
(I'm sorry that my english is bad)

**Comment by Rynnavinx** [comment]
Been sitting on this for quite a while, but it's here now!
SSPB 1.x.x versions work with mc 1.16
