### ISSUE TITLE
Sodium Shadowy Path Blocks is incompatible with Sodium 0.6.2

### ISSUE THREAD

**Issue by raspberrygitq** [Rynnavinx/sodium-shadowy-path-blocks#42]
### Log

https://mclo.gs/EgjDlza

**Comment by mrjasonn** [comment]
@Rynnavinx please fix, as doing this can add 1.21.4 support, and we would really like to see Minecraft 1.21.4 support.

**Comment by Rynnavinx** [comment]
Compatible in 4.0.0 now
